### ISSUE TITLE
nas-tools更新至2.8.2后无法使用

### ISSUE THREAD

**Issue by gZDJCVcH** [Eao-Kind/Self--use-tool#10]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>
> NASTool 版本: 2.8.2
>

## 你遇到什么问题了？
最后两行日志
【Debug】nas-tools请求发送成功
【Debug】添加站点失败，可能由于nas-tools更新导致参数不对

> 描述一下你遇到的问题
无法更新cookie或添加新站

## 你的问题能重现吗？
> 能够重现

**Comment by Eao-Kind** [comment]
v2.8.2 d8abac1 这个版本测试了一下脚本没问题可以添加，脚本升级到最新版的吗

**Comment by gZDJCVcH** [comment]
> v2.8.2 d8abac1 这个版本测试了一下脚本没问题可以添加，脚本升级到最新版的吗

脚本是2.5.0
nastools 是 v2.8.2 d91f6c7，d8abac1 更新后就到d91f6c7了

目前测试的站点 北洋园  馒头  家园  都无法添加

**Comment by Eao-Kind** [comment]
脚本需同步更新到2.8

**Comment by gZDJCVcH** [comment]
> 脚本需同步更新到2.8

![](https://s3.bmp.ovh/imgs/2023/02/01/00f0df65e59a5e97.png)
![](https://s3.bmp.ovh/imgs/2023/02/01/07d75848bbeb9577.png)
![](https://s3.bmp.ovh/imgs/2023/02/01/d974bac784560e0e.png)
脚本已更新至2.8 仍旧有该问题

**Comment by gZDJCVcH** [comment]
ptt也无法添加成功

**Comment by Eao-Kind** [comment]
拉取到了最新的代码，测试家园仍然没问题可以添加成功，确保web页面可以手动添加站点，然后脚本完全使用默认设置试试。
ptt可能是首页地址问题，在match后加上index.php

**Comment by gZDJCVcH** [comment]
> 

之前用的是beta版本油猴。换成正式版，重新安装插件并使用默认配置后恢复正常。

**Comment by Eao-Kind** [comment]
我使用的是BETA版油猴，暂时未遇到该问题，非BETA版许多COOKIE不全。
