### ISSUE TITLE
站点更新貌似会丢失之前的设置，

### ISSUE THREAD

**Issue by YoshiPark** [Eao-Kind/Self--use-tool#11]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
> V2.8.0
> NASTool 版本: vx.x.x
> V2.8.3

## 你遇到什么问题了？

> 描述一下你遇到的问题
在nastools中设置hdsky站点后，重新刷新hdsky页面，F12控制台中查询到nastools中有hdsky站点，然后成功更新cookies，但是在nastools刷新之后发现之前设置为是的使用代理和浏览器仿真选项被设置成了否，在其他一些站点也有这个问题，就是使用代理被设置成了否
## 你的问题能重现吗？

> 能够重现

**Comment by YoshiPark** [comment]
具体表现在：当【Debug】站点信息发送数据时，里面的proxy已经是true，但是刷新nastools之后，该站点的设置代理是否，没有为是，估计可能参数有问题？

**Comment by YoshiPark** [comment]
nastools作者在源代码app/sites/sites.py中写的是：
                "parse": True if site_note.get("parse") == "Y" else False,
                "unread_msg_notify": True if site_note.get("message") == "Y" else False,
                "chrome": True if site_note.get("chrome") == "Y" else False,
                "proxy": True if site_note.get("proxy") == "Y" else False,
                "subtitle": True if site_note.get("subtitle") == "Y" else False
然后我看站点信息发送数据时encodeURIComponent(JSON.stringify(data)会把proxy和chrome这些参数设置成true和false，发送到nastools后台可能就变成False了，我把js代码改了一下
data.site_note.chrome = temp.chrome 改成
if(temp.chrome == true){data.site_note.chrome = "Y";}
if(temp.chrome == false){data.site_note.chrome = "N";}
就正常了，不知道这个方法对不对，作者可以验证一下，谢谢

**Comment by Eao-Kind** [comment]
感谢指出错误之处，目前向nastools提出增加一个便于更新cookie的API的issue，若通过了则后续不再需要这么麻烦，先等几天看看。
