### ISSUE TITLE
运行脚本错误

### ISSUE THREAD

**Issue by NaviMikeW** [Eao-Kind/Self--use-tool#12]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：3.0.0
>
> NASTool 版本: v3.2.2
>

## 你遇到什么问题了？

> 在运行脚本的时候，弹出以下错误；发送到nt的cookie为空。
<img width="640" alt="image" src="https://github.com/Eao-Kind/Self--use-tool/assets/123549772/03e11f83-0d6b-4963-9871-49dac79352de">

## 你的问题能重现吗？

> 能够重现

**Comment by Eao-Kind** [comment]
是使用了BETA版的油猴吗？普通版油猴可能存在个别站点cookie为空的情况。个别站点出现cookie空还是所有站点均出现此错误，或者是有概率出现cookie为空
