### ISSUE TITLE
老哥，我这个pt站没有自动添加，是啥问题，是没有收录这个pt站吗

### ISSUE THREAD

**Issue by qiangua5210** [Eao-Kind/Self--use-tool#2]
torrentleech.org

![image](https://user-images.githubusercontent.com/24908791/188643133-06538efc-de0f-4b82-b143-173b585dfc87.png)

**Comment by Eao-Kind** [comment]
> torrentleech.org
> 
> ![image](https://user-images.githubusercontent.com/24908791/188643133-06538efc-de0f-4b82-b143-173b585dfc87.png)

文档里该站的url写错了，文档已更新，重新到文档获取新地址粘贴到match就可以了。

**Comment by qiangua5210** [comment]
> 

好的，谢谢

**Comment by qiangua5210** [comment]
老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊

**Comment by Eao-Kind** [comment]
> 老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊

用的是油猴BETA版吗，有一些站点需要用BETA版才能获取完整cookie，没有阿木童无法测试。

**Comment by qiangua5210** [comment]
> > 老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊
> 
> 用的是油猴BETA版吗，有一些站点需要用BETA版才能获取完整cookie，没有阿木童无法测试。

是用的beta，而且我在nastools里面删除站点之后，插件就不会再次添加了，

**Comment by Eao-Kind** [comment]
> > > 老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊
> > 
> > 
> > 用的是油猴BETA版吗，有一些站点需要用BETA版才能获取完整cookie，没有阿木童无法测试。
> 
> 是用的beta，而且我在nastools里面删除站点之后，插件就不会再次添加了，

访问的url是 www.torrentleech.org 吗，若后面有其他参数，不会触发脚本

**Comment by qiangua5210** [comment]
> > > > 老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊
> > > 
> > > 
> > > 用的是油猴BETA版吗，有一些站点需要用BETA版才能获取完整cookie，没有阿木童无法测试。
> > 
> > 是用的beta，而且我在nastools里面删除站点之后，插件就不会再次添加了，
> 
> 访问的url是 www.torrentleech.org 吗，若后面有其他参数，不会触发脚本

我访问的是这个，但是首页会有很多后缀出来，有影响吗

**Comment by Eao-Kind** [comment]
> > > > > 老哥，可以导入cookie 了，但是显示打不开网站，cookie过期，昨天自动添加的一个阿童木也是显示cookie过期，是什么情况啊
> > > > 
> > > > 
> > > > 用的是油猴BETA版吗，有一些站点需要用BETA版才能获取完整cookie，没有阿木童无法测试。
> > > 
> > > 
> > > 是用的beta，而且我在nastools里面删除站点之后，插件就不会再次添加了，
> > 
> > 
> > 访问的url是 [www.torrentleech.org](http://www.torrentleech.org) 吗，若后面有其他参数，不会触发脚本
> 
> 我访问的是这个，但是首页会有很多后缀出来，有影响吗

需要把后缀删除，【显示打不开网站，cookie过期】这个是什么意思，有完整的截图吗

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/188803265-6d728624-69c8-4ff6-a492-b91b427ecbe3.png)
这是首页的网址，

**Comment by qiangua5210** [comment]
![Screenshot_2022-09-07-14-21-07-709_com tencent mm](https://user-images.githubusercontent.com/24908791/188803678-a3c3472b-a8ba-4c46-b462-065138b191b7.jpg)
这个是提示

**Comment by Eao-Kind** [comment]
> ![Screenshot_2022-09-07-14-21-07-709_com tencent mm](https://user-images.githubusercontent.com/24908791/188803678-a3c3472b-a8ba-4c46-b462-065138b191b7.jpg) 这个是提示

我这边测试了一下cookie是没过期的，但部分站点签到也会显示cookie过期，可能是nas-tools判断签到的逻辑或站点管理添加的url有问题。只要资源搜索可以用就证明cookie是没问题了。

**Comment by qiangua5210** [comment]
。。。主要搜索不到。。。

**Comment by Eao-Kind** [comment]
> 。。。主要搜索不到。。。

呃，如果用了内部索引器，tl还不支持，没用阿木童暂时无法测试，如果添加的cookie是正确的（开发者工具对比一下），那就已经完成脚本的功能了。

**Comment by qiangua5210** [comment]
擦，我等等看吧，阿童木网站挂了，这个tl国外的还不支持，晚点我在测试看看

**Comment by qiangua5210** [comment]
老哥，阿童木网页可以了，但是还是签到失败，显示cookie过期，我对照了F12的cookie，一样的

**Comment by Eao-Kind** [comment]
> 老哥，阿童木网页可以了，但是还是签到失败，显示cookie过期，我对照了F12的cookie，一样的

cookie一样说明脚本正常工作了。签到失败和脚本没有关联。

**Comment by qiangua5210** [comment]
> > 老哥，阿童木网页可以了，但是还是签到失败，显示cookie过期，我对照了F12的cookie，一样的
> 
> cookie一样说明脚本正常工作了。签到失败和脚本没有关联。

我知道啥问题了，直接导入到nastools中，几个代码中间有空格，要去掉才可以🌝🌝
>

**Comment by Eao-Kind** [comment]
> > > 老哥，阿童木网页可以了，但是还是签到失败，显示cookie过期，我对照了F12的cookie，一样的
> > 
> > 
> > cookie一样说明脚本正常工作了。签到失败和脚本没有关联。
> 
> 我知道啥问题了，直接导入到nastools中，几个代码中间有空格，要去掉才可以🌝🌝
> 
> >

哪个代码有空格
