### ISSUE TITLE
最新版本nas-tools好像没法导入站点

### ISSUE THREAD

**Issue by kingjoydom** [Eao-Kind/Self--use-tool#3]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>
> NASTool 版本: v2.1.2 cdbe7c05
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 你的问题能重现吗？
![telegram-cloud-photo-size-5-6186203948512294050-y](https://user-images.githubusercontent.com/20087455/193589726-0a2f9a00-bea2-4e1c-ba5a-199bd335c878.jpg)

> 能够重现，不能够重现

**Comment by Eao-Kind** [comment]
> ## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> > 脚本 版本：
> > NASTool 版本: v2.1.2 cdbe7c05
> 
> ## 你遇到什么问题了？
> > 描述一下你遇到的问题
> 
> ## 你的问题能重现吗？
> ![telegram-cloud-photo-size-5-6186203948512294050-y](https://user-images.githubusercontent.com/20087455/193589726-0a2f9a00-bea2-4e1c-ba5a-199bd335c878.jpg)
> 
> > 能够重现，不能够重现

我更新到2.1.2查看一下，可能是nastools站点的配置更新了

**Comment by Eao-Kind** [comment]
> ## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> > 脚本 版本：
> > NASTool 版本: v2.1.2 cdbe7c05
> 
> ## 你遇到什么问题了？
> > 描述一下你遇到的问题
> 
> ## 你的问题能重现吗？
> ![telegram-cloud-photo-size-5-6186203948512294050-y](https://user-images.githubusercontent.com/20087455/193589726-0a2f9a00-bea2-4e1c-ba5a-199bd335c878.jpg)
> 
> > 能够重现，不能够重现

大概知道原因了，当没有站点的时候直接返回了false。试试先在nastools里面手动添加一个站点，然后再用脚本看看能不能添加成功
