### ISSUE TITLE
不能够导入成功

### ISSUE THREAD

**Issue by amomo-001** [Eao-Kind/Self--use-tool#4]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>
> NASTool 版本: v2.1.3
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
直接就没有cookie的获取
## 你的问题能重现吗？

> 能够重现
![1664934199673](https://user-images.githubusercontent.com/61110958/193961629-d631e0d6-5813-4a36-8164-1a8fc31380ac.jpg)

**Comment by Eao-Kind** [comment]
> ## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> > 脚本 版本：
> > NASTool 版本: v2.1.3
> 
> ## 你遇到什么问题了？
> > 描述一下你遇到的问题
> > 直接就没有cookie的获取
> 
> ## 你的问题能重现吗？
> > 能够重现
> > ![1664934199673](https://user-images.githubusercontent.com/61110958/193961629-d631e0d6-5813-4a36-8164-1a8fc31380ac.jpg)

访问nastools失败，查看一下ip地址和秘钥有没有正确填写。

**Comment by amomo-001** [comment]
解决了，好像是密钥没有正确，pt.btschool.club这个站好像不会导入，插件没有反应

**Comment by Eao-Kind** [comment]
> 解决了，好像是密钥没有正确，pt.btschool.club这个站好像不会导入，插件没有反应

是个Bug，修复了，更新一下脚本。有盾的站点进去后再刷新一次。

**Comment by amomo-001** [comment]
好像还是不行，没有反应，插件已经更新过了

**Comment by Eao-Kind** [comment]
> 好像还是不行，没有反应，插件已经更新过了

我这里没有问题，发一下控制台日志

**Comment by amomo-001** [comment]
![image](https://user-images.githubusercontent.com/61110958/194063270-9e5dc8b1-f2ca-4149-bad6-698afcffd057.png)
需要beat版

**Comment by Eao-Kind** [comment]
> ![image](https://user-images.githubusercontent.com/61110958/194063270-9e5dc8b1-f2ca-4149-bad6-698afcffd057.png) 需要beat版

挺多站点都需要用BETA版油猴的。建议更换

**Comment by amomo-001** [comment]
好的
