### ISSUE TITLE
油猴脚本match错误

### ISSUE THREAD

**Issue by imkratos** [Eao-Kind/Self--use-tool#5]
// @match   https://www.pttime.org/index.php
pttime 这行没有 index.php 

// @mathc   https://www.carpet.net/index.php
这行match拼写错误

**Comment by Eao-Kind** [comment]
> // @match https://www.pttime.org/index.php pttime 这行没有 index.php
> 
> // @mathc https://www.carpet.net/index.php 这行match拼写错误

糟糕，大意了，感谢提醒
