### ISSUE TITLE
馒头站cookie获取不到

### ISSUE THREAD

**Issue by imkratos** [Eao-Kind/Self--use-tool#6]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本： 2.3.1
>
> NASTool 版本: 最新
>

## 你遇到什么问题了？

> 馒头站 获取不到cookie ， 控制台打印了一下，发现document.cookie 是取不到cookie的，很奇怪。

## 你的问题能重现吗？

> 不知道是我自己单独的问题，还是都有。

**Comment by Eao-Kind** [comment]
用BETA版油猴
