### ISSUE TITLE
新版本似乎不能用了

### ISSUE THREAD

**Issue by SouL87a** [Eao-Kind/Self--use-tool#7]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
> 2.3.1
> NASTool 版本: vx.x.x
>2.5.1（2.5.0）

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/44329481/203481281-cd1b6780-dc11-484d-8312-87c9972f6095.png)

> 描述一下你遇到的问题
无法发送添加站点发送cookie
## 你的问题能重现吗？
能够重现

我不确定是不是新版本的问题，因为我重装系统重新装了脚本。。。

**Comment by Eao-Kind** [comment]
应该是nastools更新了，过两天装一下2.5.1再更新

**Comment by imkratos** [comment]
2.5.1 新版本同不能用，应该是API 或者是参数发生了变更

**Comment by Eao-Kind** [comment]
已更新，可以试一下

**Comment by SouL87a** [comment]
> 已更新，可以试一下

感谢更新
