### ISSUE TITLE
nastools同个站点设置了多个站点维护（比如签到一个，其他功能一个），但cookie貌似只更新一个

### ISSUE THREAD

**Issue by YoshiPark** [Eao-Kind/Self--use-tool#8]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>
> NASTool 版本: v2.5.0
>

弄了两个瓷器站点维护，一个用来签到，一个用来数据统计和刷流，更新cookie时只更新其中签到那个

> 描述一下你遇到的问题

## 你的问题能重现吗？

> 能够重现

**Comment by Eao-Kind** [comment]
为什么要分开2个，直接一个不可以吗？应该不多人需要这样弄吧

**Comment by YoshiPark** [comment]
> 为什么要分开2个，直接一个不可以吗？应该不多人需要这样弄吧

首先感谢大佬提供这样的插件，是这样的，签到页面得设置一个，就是后缀attentance.php设置一个（有些网站按签到按钮有魔力），然后刷流和数据统计就是正常的界面设置一个，所以总共是两个，如果大佬有兴趣就弄一下吧，谢谢了！

**Comment by Eao-Kind** [comment]
> > 为什么要分开2个，直接一个不可以吗？应该不多人需要这样弄吧
> 
> 首先感谢大佬提供这样的插件，是这样的，签到页面得设置一个，就是后缀attentance.php设置一个（有些网站按签到按钮有魔力），然后刷流和数据统计就是正常的界面设置一个，所以总共是两个，如果大佬有兴趣就弄一下吧，谢谢了！

站点url设置成index.php并没有问题，可以开启模拟仿真试试，nastools签到代码中包含了attentance.php，它会自动尝试签到
SITE_CHECKIN_XPATH = [
    '//a[contains(@href, "attendance.php")]',
]

**Comment by YoshiPark** [comment]
> > > 为什么要分开2个，直接一个不可以吗？应该不多人需要这样弄吧
> > 
> > 
> > 首先感谢大佬提供这样的插件，是这样的，签到页面得设置一个，就是后缀attentance.php设置一个（有些网站按签到按钮有魔力），然后刷流和数据统计就是正常的界面设置一个，所以总共是两个，如果大佬有兴趣就弄一下吧，谢谢了！
> 
> 站点url设置成index.php并没有问题，可以开启模拟仿真试试，nastools签到代码中包含了attentance.php，它会自动尝试签到 SITE_CHECKIN_XPATH = [ '//a[contains(@href, "attendance.php")]', ]

好的谢谢，整理了一下，有些站点就不是用这个“attendance.php”来签到的，这种有没有解决办法

**Comment by Eao-Kind** [comment]
> > > > 为什么要分开2个，直接一个不可以吗？应该不多人需要这样弄吧
> > > 
> > > 
> > > 首先感谢大佬提供这样的插件，是这样的，签到页面得设置一个，就是后缀attentance.php设置一个（有些网站按签到按钮有魔力），然后刷流和数据统计就是正常的界面设置一个，所以总共是两个，如果大佬有兴趣就弄一下吧，谢谢了！
> > 
> > 
> > 站点url设置成index.php并没有问题，可以开启模拟仿真试试，nastools签到代码中包含了attentance.php，它会自动尝试签到 SITE_CHECKIN_XPATH = [ '//a[contains(@href, "attendance.php")]', ]
> 
> 好的谢谢，整理了一下，有些站点就不是用这个“attendance.php”来签到的，这种有没有解决办法

nastools可以签大部分了，不行的站点可以去那边提问，有一个issues专门收集反馈
