### ISSUE TITLE
后台F12报错

### ISSUE THREAD

**Issue by naoki66** [Eao-Kind/Self--use-tool#9]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>PtSiteToNas-toolsv2.5.0
> NASTool 版本: vx.x.x
>v2.6.0 b00e4220

## 你遇到什么问题了？
【Debug】nas-tools请求发送成功
然后后面还有
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at userscript.html?name=PT%2XXXXXXXXX.user.js&id=XXXXXXXXXXXeb7124ea4cb4:218:18
> 描述一下你遇到的问题

## 你的问题能重现吗？
能
> 能够重现，不能够重现
F5刷新页面

**Comment by naoki66** [comment]
http://hdzone.me/index.php
userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')
    at userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167:18
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167
setTimeout(异步)
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:47
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:270
St @ VM186:9
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:1
window.__f__lb61zvv4.84 @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:1
St @ VM186:9
n @ VM186:71
(匿名) @ VM186:73
p @ VM186:68
yt @ VM184 content.js:7
p @ VM184 content.js:53
m @ VM184 content.js:55
send @ VM184 content.js:55
(匿名) @ VM184 content.js:40
(匿名) @ VM184 content.js:19
setTimeout(异步)
(匿名) @ VM184 content.js:19
On.addEventListener.Mt.capture @ VM184 content.js:15
userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')
    at userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167:18
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:167
setTimeout(异步)
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:47
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:270
St @ VM258:9
(匿名) @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:1
window.__f__lb636nao.lwh @ userscript.html?name=PT%AAAAAAAA.user.js&id=BBBBBBBB:1
St @ VM258:9
n @ VM258:71
(匿名) @ VM258:73
p @ VM258:68
yt @ content.js:7
p @ content.js:53
m @ content.js:55
send @ content.js:55
(匿名) @ content.js:40
(匿名) @ content.js:19
setTimeout(异步)
(匿名) @ content.js:19
On.addEventListener.Mt.capture @ content.js:15

**Comment by Eao-Kind** [comment]
脚本可以让nastools可以添加站点吗，这个错误在谷歌浏览器下没遇到过

**Comment by naoki66** [comment]
> 脚本可以让nastools可以添加站点吗，这个错误在谷歌浏览器下没遇到过

userscript.html?name=~~~~~~~~~~~~~~~~~~~~~~~~.user.js&id=~~BBBBBB~~~~:51 [UserJS] INF Loading...
userscript.html?name=~~~~~~~~~~~~~~~~~~~~~~~~.user.js&id=~~BBBBBB~~~~:50 [UserJS] DBG Config: Object
userscript.html?name=~~~~~~~~~~~~~~~~~~~~~~~~.user.js&id=~~BBBBBB~~~~:51 [UserJS] INF Injecting Container...
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~151 【Debug】开始获取PT站点信息
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~159 【Debug】cookie: ````````````````````````````````````
userscript.html?name=~~~~~~~~~~~~~~~~~~~~~~~~.user.js&id=~~BBBBBB~~~~:51 [UserJS] INF Progress: -2%
userscript.html?name=~~~~~~~~~~~~~~~~~~~~~~~~.user.js&id=~~BBBBBB~~~~:51 [UserJS] INF Progress: -3065%
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~111 【Debug】nas-tools请求userSite成功,status: 0
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~190 【Debug】查询到nas-tools中该站点的信息: ourbits
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~147 【Debug】站点信息发送完毕
userscript.html?name=PtSiteToNas-tools.user.js&id=~~BBBBBB~~~~138 【Debug】nas-tools请求发送成功

似乎只有部分网站出现这种情况，其他正常
出现此错误的比如：
hdsky pttime.org  pterclub

**Comment by Eao-Kind** [comment]
hdsky 、 pterclub两个这边都可以正常发送，暂时无法复现。hds更新cookie可以成功吗，可以的话暂时先不管了。
